### ISSUE TITLE
Any instructions on how to use this?

### ISSUE THREAD

**Issue by Oaklight** [ChingCdesu/supernode-frontend#1]

**Comment by ChingCdesu** [comment]
I will upload a doc in few days

**Comment by ChingCdesu** [comment]
> I will upload a doc in few days

NOTICE:
* No GUI client provided
* Translations have not completed yet
* Server CANNOT hold on too many devices and it is unstable

**Comment by ChingCdesu** [comment]
@Oaklight 
Basic installation guide has been updated.
For more information of supernode configurations, please check [appconfig.example.yaml](https://github.com/ChingCdesu/supernode-server/blob/main/appconfig.example.yaml).

**Comment by Oaklight** [comment]
Thank you. 

> * No GUI client provided
> * Translations have not completed yet
> * Server CANNOT hold on too many devices and it is unstable

The website panel is good enough. This is actually better than a GUI client IMHO.
Translation is not an issue.
What do you mean "too many devices"? By "server", do you mean n2n supernode or this web panel?

> @Oaklight Basic installation guide has been updated. For more information of supernode configurations, please check [appconfig.example.yaml](https://github.com/ChingCdesu/supernode-server/blob/main/appconfig.example.yaml).

~Is it possible to upload a docker-compose.yaml as well? I think most people use n2n is for self-hosted services or such. We are more acquainted with Docker compared to K8s.~ I see you already have a docker-compose file. Thanks.
Is it possible to use the natively installed n2n supernode, instead of a dockerized supernode?

**Comment by ChingCdesu** [comment]
> ~Is it possible to upload a docker-compose.yaml as well? I think most people use n2n is for self-hosted services or such. We are more acquainted with Docker compared to K8s.~ I see you already have a docker-compose file. Thanks. Is it possible to use the natively installed n2n supernode, instead of a dockerized supernode?

You can follow instructions step by step:
1. Start a postgresql/mysql server (optional, without postgresql/mysql, server will fallback to sqlite)
2. Start a redis server
3. Clone and build [supernode-frontend](https://github.com/ChingCdesu/supernode-frontend) and [supernode-server](https://github.com/ChingCdesu/supernode-server)
  * You need nodejs, g++, cmake, ninja, emscripten in your environment
4. Change settings in `appconfig.example.yaml`, and rename it to `appconfig.yaml`
5. Run supernode-frontend and supernode-server
6. Start up a nginx server, and configure it with [configuration file](https://github.com/ChingCdesu/supernode-frontend/blob/main/deploy/nginx/default.conf.template)

**Comment by ChingCdesu** [comment]
Run natively is a little bit hard, I have no experience to manage Linux packages.

> What do you mean "too many devices"? By "server", do you mean n2n supernode or this web panel?

Means I have not tested in n2n cluster mode and I don't know what will happened if joined a lot of devices to one node. Because of Node.js is running on single thread, easily make it overload.

**Comment by Oaklight** [comment]
> Run natively is a little bit hard, I have no experience to manage Linux packages.
> 
> > What do you mean "too many devices"? By "server", do you mean n2n supernode or this web panel?
> 
> Means I have not tested in n2n cluster mode and I don't know what will happened if joined a lot of devices to one node. Because of Node.js is running on single thread, easily make it overload.

Could you enlighten me about what is nodejs doing in supernode-server? I'm not familiar with node or js. Figuring out the difference btw your supernode-server vs original n2n v3 would potentially help us move along with this direction.

**Comment by ChingCdesu** [comment]
> Could you enlighten me about what is nodejs doing in supernode-server? I'm not familiar with node or js. Figuring out the difference btw your supernode-server vs original n2n v3 would potentially help us move along with this direction.

N2N is written in C, supernode-server make a binding for N2N with dynamic library mode, so js can call functions from native C code, this part is in [native folder in supernode-server](https://github.com/ChingCdesu/supernode-server/tree/main/native). Data transfer like this: `N2N Library -> C-JS Wrapper -> JS Runtime -> Nest.js Server`.

Because of Nest.js provide a high-level language features, like `decorator`, `event system` etc. You can build a functional server quickly, and people who experienced on javascript understand code easily.

Original n2n v3 server is running with a configuration file and a community file, supernode-server save data in a database.

Also, supernode-server has a web based user interface and admin interface. It allows you make permission restrictions, and it allows you login with OIDC(OAuth2), you can configure the system login with Microsoft, Google, and other platforms support OIDC authentication.
